version: '3'

networks:
  proxy:
    driver: bridge

services:
  nginx:
    restart: always
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    networks:
      - proxy

  web-blue-01:
    restart: always
    image: nginx
    volumes:
      - ./azul.html:/usr/share/nginx/html/index.html
      - ./:/usr/share/nginx/html
    networks:
      - proxy

  web-blue-02:
    restart: always
    image: nginx
    volumes:
      - ./azul.html:/usr/share/nginx/html/index.html
      - ./:/usr/share/nginx/html
    networks:
      - proxy

  web-green-01:
    restart: always
    image: nginx
    volumes:
      - ./verde.html:/usr/share/nginx/html/index.html
      - ./:/usr/share/nginx/html
    networks:
      - proxy

  web-green-02:
    restart: always
    image: nginx
    volumes:
      - ./verde.html:/usr/share/nginx/html/index.html
      - ./:/usr/share/nginx/html
    networks:
      - proxy